# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

management:
    endpoints:
        web:
            base-path: /actuator
            exposure:
                include: ["configprops", "env", "health", "info", "threaddump", "metrics"]
    endpoint:
        health:
            show-details: when-authorized
spring:
    application:
        name: chaka-demo
    profiles:
        # The commented value for `active` can be replaced with valid Spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: #spring.profiles.active#