logging:
    level:
        ROOT: INFO

server:
    port: 8080

spring:
    profiles:
        active: dev
        include: 
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false
    output:
      ansi:
        enabled: always
        
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: root  
        password:
    # H2 Web Console 
    h2:
        console:
            enabled: true
            path: /h2-console
    # JPA
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true