version: '2'
services:
    db:
        image: mysql:5.7.20
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=demo
        ports:
            - 3306:3306
#        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestampi
    adminer:
        image: adminer
        restart: always
        ports:
          - 8081:8080
